### ISSUE TITLE
[Enhancement] Can it be made to full-fledged network client

### ISSUE THREAD

**Issue by pocha** [saravana815/dhtest#12]
Hi Sarvana, 

 Good job with the code. 

 I have been working on [Griggi](www.griggi.com) & we have to constantly deploy newer version of Openwrt router with our changes on top of it. I am looking to have a testing setup where I could run one (or more) full-fledged network client, that connects to the router, does some network activity like downloading/uploading some data, go off the network, come back & repeat. 

 This project looks like a good starting point for it. Can you pass me some links as to how this can be extended. I am an application layer guy & very much a noob when it comes to mac layer of things. 

Thanks
Ashish

**Comment by tomaszmrugalski** [comment]
Hey Ashish!
There's perfdhcp in the [Kea project](https://github.com/isc-projects/kea). See in src/bin/perfdhcp. It can simulate many DHCP clients, both v4 and v6. I can't simulate the whole client box, but it can hammer your DHCP server with heavy traffic if you want to. 

Hope that helps,
Tomek

**Comment by saravana815** [comment]
Hi Ashish,
This client tool does not have tcp/ip stack integrated in it. 
What you are asking is basically a user space network stack. Seems there is project called nuse which can emulate user space network stack and it seems all linux networking utilities can be used on top of it. I think it can do dhcp also. Try it.
http://libos-nuse.github.io/
https://github.com/libos-nuse/net-next-nuse

Regards,
Saravana

**Comment by pocha** [comment]
Thanks @tomaszmrugalski @saravana815 for your inputs. Will give both a shot & drop a word here as to which one I ended up using.
