### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by trettet** [saravana815/dhtest#21]
Everytime I run this program to test DHCP I get this Socket error

![image](https://user-images.githubusercontent.com/1276544/40514843-42d4c5d8-5fdd-11e8-8db1-c9fc03885f1c.png)

**Comment by trettet** [comment]
Even running it with root
![image](https://user-images.githubusercontent.com/1276544/40514986-a97deed6-5fdd-11e8-938a-078894f97f3c.png)

**Comment by trettet** [comment]
Running on Ubuntu 18.04 on Windows Linux Subsystem

**Comment by saravana815** [comment]
Hi trettet, 

I am not sure whether the windows linux subsystem provides the API for L2 RAW socket creation ie "sock_packet = socket(PF_PACKET, SOCK_RAW, htons(ETH_P_ALL));". 
https://www.linuxjournal.com/article/4659

I need to check on this. Basically the tool requires a L2 RAW socket which is provided by OS. If linux sub system provided by windows does not support this, then we have to look for some around ways only. 

Regards,
Saravana

**Comment by saravana815** [comment]
Hi Trettet, 

The WSL does not support PF_PACKET socket. There is a github issue reported on WSL on the same - https://github.com/Microsoft/WSL/issues/1628

Regards,
Saravana
