### ISSUE TITLE
Invalid checksum

### ISSUE THREAD

**Issue by OnlyInAmerica** [saravana815/dhtest#28]
I'm occasionally able to generate packets with invalid UDP checksums using commands of the form `dhtest -m 38:f9:d3:00:00:35 -i eth0`.

See raw packet and `tcpdump -vv` taken from sending host.
[dhtest_bad_request.txt](https://github.com/saravana815/dhtest/files/4162667/dhtest_bad_request.txt)

Built from da07f6ee4dbecef4d6bf366ab97bd6a3df7223de.

**Comment by saravana815** [comment]
Hi, Can you try with the latest master branch? There were fixes on the checksum
