### ISSUE TITLE
rfc3442-classless-static-routes support

### ISSUE THREAD

**Issue by renard** [saravana815/dhtest#3]
Hi,

This is a nice tool.

Do you plan to add support for rfc3442-classless-static-routes (option 121) to debug static route returned by the server?

Cheers

**Comment by saravana815** [comment]
Hi Renard,

A debug parser can be added to print the static routes option 121. Would like to the RFC and option format. i think this can be added easily. 

Regards,
Saravana

**Comment by mxn7** [comment]
Hi,

How can we send max size packet of dhcp containing the maximum data in it so that we break the standard size allocated to dhcp packet by CPE (or Access point) ?

**Comment by saravana815** [comment]
Hi,

The tool basically sets the packet size based on the options given in the command line.  
Suppose if you want the dhcp packet size to be bigger than 600 bytes, you can try passing multiple custom options each with 255 bytes long. 

Regards,
Saravana

**Comment by mxn7** [comment]
Hi Saravana,

I tried it .

Here is below command i am giving it.
./dhtest -m 00:0E:8E:DE:F3:5A -f -i sta11 -c 82,hex,7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff -c 82,hex,7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff -c 82,hex,7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff -c 82,hex,7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff7fffffffffffffff
Segmentation fault
 

 one -c gives around 64B  

by using -c..we can go upto a max of 700B 

What i wish is to send the packet with size more than 6KB to achieve what i am looking for.
can you suggest how can i achieve the same, and what line of code, Do i need to change in your source code.

**Comment by saravana815** [comment]
Hi,

The tools uses a buffer size of 1518 (inludes all headers - l2 to l4 and dhcp) for the DHCP packets discover, offer, request and ack.  So by packing multiple options, i think it should be possible to generate upto a packet size of 1500 (IP + dhcp header + dhcp options). 

For your question of 6KB packet size, the tool wont be able to generate such a big packet since it requires IP fragmentation which the tool does not do.  

Regards,
Saravana

**Comment by mxn7** [comment]
If in your source code, we change the size from 1500 to 9000, would it generate the packet with that size ?
or will it fragment it and if so how can we avoid fragmentation of this to achieve the jumbo packets with required length?

Best Regards,
Manoj

**Comment by saravana815** [comment]
Hi Manoj,

Workaround fix

Enable the NIC for jumbo frames and set the DHCP packet buffer and DHCP
option buffer size to 9000.
Add new command line option that would add a dhcp option to option buffer
to the length specified in argument.

Clean fix
Get the NIC MTU from code and set the dhcp packet buffer and option buffer.
Add new command line option that would add a dhcp option to option buffer
to the length specified in argument.

Regards,
Saravana
