### ISSUE TITLE
Enhancement to support dhcpv6

### ISSUE THREAD

**Issue by deepikasansuddi** [saravana815/dhtest#32]
Hi Saravana,
This is a very helpful tool. Can there be an enhancement for v6 support or would you know of any other such available tools?
Thanks, 
Deepika.

**Comment by saravana815** [comment]
Hi Deepika,
The better option to write the ipv6 dhcp test tool would be python for sure. 
I am not working on this tool nor on ipv6 flavor of this tool. 
Regards,
Saravana
